# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b587193c4a84f0d6dc2f582f339fb78668ee9e10c255199cec7a67c830a2452aaf26222b7157fffcbe19179f3ae9e0e512d4080d715d9952ab9107cb2751313

test:
  secret_key_base: d13975d954e30602409daed51b9cbf88b94bf70687f010a5d6e531ef7f883659d192466ea0d57162a6587f7b499bd4c6ef4be33becd393140551223271864322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
